// 拉丁输入（全拼/首字母）到页面的映射。仅在中文文本匹配完全落空时启用，
// 用于「打开cgd」这类拼音输入；词条按页面人工维护，新增页面时同步补齐。
export const agentPagePinyinAliases: Record<string, string[]> = {
  'dashboard.overview': ['yibiaopan', 'ybp', 'shouye', 'gongzuotai', 'gzt', 'yunyingzonglan', 'yyzl'],
  'system.personnel': ['renshiziliaoguanli', 'rszlgl', 'yuangongziliao', 'ygzl', 'yuangongguanli', 'yggl'],
  'system.organization': ['zuzhijigouguanli', 'zzjggl', 'zuzhijiagou', 'zzjg', 'bumen'],
  'system.position': ['gangweiguanli', 'gwgl', 'gangwei', 'zhiwei'],
  'system.roles': ['jueseguanli', 'jsgl', 'juese', 'quanxianjuese'],
  'system.admin': ['guanliyuan', 'gly', 'ziguanliyuan'],
  'system.area': ['xingzhengquhua', 'xzqh', 'diquguanli', 'dqgl'],
  'system.logs': ['fangwenrizhi', 'fwrz', 'caozuorizhi', 'czrz', 'xitongrizhi', 'xtrz'],
  'system.online': ['zaixianyonghu', 'zxyh', 'zaixianrenyuan', 'zxry'],
  'customer.type': ['kehuleixing', 'khlx', 'kehufenlei', 'khfl'],
  'customer.new': ['xinkaituokehu', 'xktkh', 'xinkehu', 'xkh', 'qianzaikehu', 'qzkh'],
  'customer.info': ['kehuziliao', 'khzl', 'kehuxinxi', 'khxx', 'kehudangan', 'khda', 'zhengshikehu', 'zskh'],
  'customer.public': ['gonghaikehu', 'ghkh', 'kehugonghai', 'khgh', 'daifenpeikehu'],
  'customer.region': ['kehuquyu', 'khqy', 'xiaoshouquyu', 'xsqy', 'quyuguanli', 'qygl'],
  'customer.finance.credit': ['kehushouxinyuebiao', 'khsxyb', 'kehushouxin', 'khsx', 'shouxinyue'],
  'customer.finance.prepay': ['yufukuanyuebiao', 'yfkyb', 'kehuyufukuan', 'khyfk', 'yucunkuan'],
  'customer.finance.gift': ['zengsongjineyuebiao', 'zsjeyb', 'kehuzengsongjine', 'khzsje', 'zengsongyue'],
  'customer.finance.balance': ['kehuyuebiao', 'khyb', 'kehuyue', 'khy'],
  'customer.task.visit': ['baifangrenwudan', 'bfrwd', 'kehubaifang', 'khbf', 'baifangrenwu', 'bfrw', 'baifangjihua'],
  'product.category': ['chanpinleibie', 'cplb', 'chanpinfenlei', 'cpfl', 'shangpinleibie', 'splb'],
  'product.unit': ['jiliangdanwei', 'jldw', 'chanpindanwei', 'cpdw', 'danweishezhi'],
  'product.info': ['chanpinziliao', 'cpzl', 'chanpindangan', 'cpda', 'shangpinziliao', 'spzl', 'chanpinxinxi', 'cpxx'],
  'product.unsold': ['zhixiaochanpin', 'zxcp', 'zhixiaoshangpin', 'zxsp'],
  'warehouse.location': ['kuweiguanli', 'kwgl', 'cangchukuwei', 'cckw', 'kuwei'],
  'warehouse.shelf': ['fanghuohuowei', 'fhhw', 'huojiaguanli', 'hjgl', 'huojia'],
  'warehouse.plastic': ['suliaoheguanli', 'slhgl', 'suliaohe', 'slh', 'zhouzhuanxiang', 'zzx'],
  'warehouse.stock': ['chanpinkucun', 'cpkc', 'shangpinkucun', 'spkc', 'kucun', 'kucunchaxun', 'kccx'],
  'warehouse.printer.model': ['dayinjixinghao', 'dyjxh', 'xinghaopeizhi', 'xhpz'],
  'purchase.supplier.type': ['gongyingshangleixing', 'gyslx', 'gongyingshangfenlei', 'gysfl'],
  'purchase.supplier': ['gongyingshangdangan', 'gysda', 'gongyingshangziliao', 'gyszl', 'gongyingshang', 'gys', 'gonghuoshang', 'ghs'],
  'purchase.supplier.credit': ['gongyingshangshouxin', 'gyssx', 'gongyingshangshouxinyue', 'gyssxy'],
  'purchase.supplier.gift': ['gongyingshangzengsongjine', 'gyszsje', 'gongyingshangzengsongyue', 'gyszsy'],
  'purchase.order': ['caigoudingdan', 'cgdd', 'caigoudan', 'cgd', 'caigoukaidan', 'cgkd', 'jinhuodan'],
  'purchase.inbound': ['caigourukudan', 'cgrkd', 'caigouruku', 'cgrk', 'rukudan', 'shouhuodan'],
  'purchase.return': ['caigoutuihuodan', 'cgthd', 'caigoutuihuo', 'cgth', 'gongyingshangtuihuo', 'gysth'],
  'purchase.report.return-summary': ['caigoutuihuihuizongbiao', 'cgthhzb', 'caigoutuihuihuizong', 'cgthhz', 'gongyingshangtuihuotongji', 'gysthtj'],
  'purchase.report.inbound-detail': ['caigourukudanmingxi', 'cgrkdmx', 'caigourukumingxi', 'cgrkmx', 'rukushangpinmingxi', 'rkspmx'],
  'purchase.report.supplier-balance': ['gongyingshangyuebiao', 'gysyb', 'gongyingshangyue', 'gysy', 'gongyingshangwanglai', 'gyswl'],
  'sales.order': ['xiaoshoudingdan', 'xsdd', 'xiaoshoudan', 'xsd', 'xiaoshoukaidan', 'xskd', 'kaidan'],
  'sales.customer-order': ['kehudinghuodan', 'khdhd', 'kehudinghuo', 'khdh', 'dinghuodan'],
  'sales.return': ['xiaoshoutuihuodan', 'xsthd', 'xiaoshoutuihuo', 'xsth', 'kehutuihuo', 'khth'],
  'sales.reconciliation': ['xiaoshouduizhangdan', 'xsdzd', 'xiaoshouduizhang', 'xsdz', 'kehuduizhang', 'khdz', 'duizhangdan'],
  'sales.report.product-summary': ['chanpinxiaoshouhuizongbiao', 'cpxshzb', 'chanpinxiaoshouhuizong', 'cpxshz', 'chanpinxiaoliang', 'cpxl', 'xiaoliangpaihang', 'xlph'],
  'sales.report.customer-summary': ['kehuxiaoshouhuizongbiao', 'khxshzb', 'kehuxiaoshouhuizong', 'khxshz', 'kehuxiaoshoutongji', 'khxstj'],
  'sales.report.order-detail': ['xiaoshoudingdanmingxibiao', 'xsddmxb', 'xiaoshoudingdanmingxi', 'xsddmx', 'xiaoshoushangpinmingxi', 'xsspmx'],
  'sales.report.customer-order-detail': ['kehudinghuomingxibiao', 'khdhmxb', 'kehudinghuomingxi', 'khdhmx'],
  'delivery.task': ['peisongrenwudan', 'psrwd', 'peisongrenwu', 'psrw', 'peisongdan', 'psd', 'songhuorenwu', 'shrw'],
  'delivery.logistics': ['wuliudanhaoguanli', 'wldhgl', 'wuliudanhao', 'wldh', 'kuaidadanhao', 'kddh', 'yundanhao'],
  'delivery.driver': ['sijidangan', 'sjda', 'jiashiyuan', 'jiashiyuandangan'],
  'delivery.vehicle': ['cheliangguanli', 'clgl', 'cheliangdangan', 'clda', 'cheliang', 'songhuoche'],
  'delivery.company': ['wuliugongsi', 'wlgs', 'chengyunshang', 'cys', 'kuaidigongsi', 'kdgs', 'yunshugongsi', 'ysgs'],
  'finance.subject': ['kemuguanli', 'kmgl', 'caiwukemu', 'cwkm', 'kuaijikemu', 'kjkm'],
  'finance.bank-account': ['yinhangzhanghu', 'yhzh', 'gongsiyinhangka', 'shoukuanzhanghu', 'skzh'],
  'finance.other-receipt': ['qitashoukuan', 'qtsk', 'qitashouru', 'qtsr', 'zaxiangshoukuan'],
  'finance.transfer': ['shoukuandan', 'skd', 'xiaoshoushoukuan', 'xssk', 'kehufukuan', 'khfk', 'shoudaodehuokuan', 'sddhk'],
  'finance.gift': ['yuejieshoukuandan', 'yjskd', 'yuejieshoukuan', 'yjsk'],
  'finance.precollection': ['yushoukuandan', 'yskd', 'yushoukuan', 'ysk', 'kehuyushou', 'khys'],
  'finance.payment-order': ['fukuandan', 'fkd', 'gongyingshangfukuan', 'gysfk', 'fukuanguanli', 'fkgl'],
  'finance.monthly-payment': ['yuejiefukuandan', 'yjfkd', 'yuejiefukuan', 'yjfk'],
  'finance.prepayment': ['yufukuandan', 'yfkd', 'caigouyufukuan', 'cgyfk', 'yufukuanguanli', 'yfkgl'],
  'finance.other-payment': ['qitafukuan', 'qtfk', 'qitazhichu', 'qtzc', 'zaxiangfukuan'],
  'profile.center': ['gerenzhongxin', 'grzx', 'wodeziliao', 'wdzl', 'gerenxinxi', 'grxx', 'zhanghaoxinxi', 'zhxx'],
  'profile.change-password': ['xiugaimima', 'xgmm', 'genggaimima', 'ggmm', 'chongzhimima', 'czmm'],
  'profile.my-visit-task': ['fuzaibaifangrenwu', 'fzbfrw', 'wodebaifangrenwu', 'wdbfrw', 'wodebaifangjilu', 'wdbfjl'],
}
